### ISSUE TITLE
dragDrop don't work

### ISSUE THREAD

**Issue by kgricour** [tongyy/react-native-draggable#20]
hi, i have pressDrag that don't work, Why ? the others props are ok
`<Draggable renderShape='image' imageSource={this.state.buttoncamera} renderSize={56} renderColor='transparent' offsetX={-100} offsetY={-200} pressDrag={()=>console.log('touched!!')}/>`

**Comment by tongyy** [comment]
It works. Can you give us some further detail as follows?
1. OS version
2. lib version
3. device or emulator

**Comment by tongyy** [comment]
2.lib ( is your lib is the latest ? react-native-draggable:1.0.14)
3.device  (ios or android?) 

You can use "pressInDrag" instead of "pressDrag" for a workaround. Basically, pressInDrag and pressDrag are the same. Their priority are pressInDrag->pressOutDrag->pressDrag.
By the way, these events should work well at the same time.

**Comment by kgricour** [comment]
ok thanks it's work . thank you very much for your times

**Comment by Eramirez0633** [comment]
I just want to trigger an action when the user press the buttton not when the user drag the button may someone help me?

**Comment by tongyy** [comment]
have you tried three press api which are pressInDrag, pressOutDrag and pressDrag?

**Comment by siyukok** [comment]
> I just want to trigger an action when the user press the buttton not when the user drag the button may someone help me?
> 
> This doesn't work on android

+1

**Comment by tongyy** [comment]
it has fixed in Version 2.0.0
