### ISSUE TITLE
Save the latest X and Y to be able to render the same look 

### ISSUE THREAD

**Issue by sadiebarani** [tongyy/react-native-draggable#52]
Hi,
I need to be able to save the X and Y location of the component after it is moved by the user so I can render it (for example the next day ) that he connects with the look that he prefers.
I've tried followings, but none works as expected.

const [item01X, setItem01X] = useState(30);
  const [item01Y, setItem01Y] = useState(50);

const OnDraghandler01 = (itm01X, itm01Y) => {
    setItem01X(itm01X);
    setItem01Y(itm01Y);
    return;
  };

1-
 onDragRelease={(gestureState) =>
            OnDraghandler01(
              gestureState.nativeEvent.pageX,
              gestureState.nativeEvent.pageY,
                         )
          }
2-
onDragRelease={(getPosition) =>
            OnDraghandler02(
              getPosition.nativeEvent.locationX,
              getPosition.nativeEvent.locationY
            )
          }

appreciate your help.
thanks
SB

**Comment by allandiego** [comment]
I dont think its possible at the moment, i have done something similar with some modifications, the x y you look for to save and use for future renders are stored in the lib code part:
```js
const pan = new Animated.ValueXY();
```
 You need save the values of x y after user moviment ends, so i have passed a function as a prop to execute inside the drag component where we have access to x y onDragReleaseSavePosition()
```js
      onPanResponderRelease: (e, gestureState) => {
        pan.flattenOffset();

        if (onDragReleaseSavePosition) {
          onDragReleaseSavePosition(id, pan.x._value,  pan.y._value);
        }
      },
```

**Comment by tongyy** [comment]
Hey guys,
onDragRelease function has two arguments passed which are Event and GestureState
Check this out  [Gesture and Event](https://reactnative.dev/docs/panresponder)

gestureState object has the following:
stateID - ID of the gestureState- persisted as long as there at least one touch on screen
moveX - the latest screen coordinates of the recently-moved touch
moveY - the latest screen coordinates of the recently-moved touch
x0 - the screen coordinates of the responder grant
y0 - the screen coordinates of the responder grant
dx - accumulated distance of the gesture since the touch started
dy - accumulated distance of the gesture since the touch started
vx - current velocity of the gesture
vy - current velocity of the gesture
numberActiveTouches - Number of touches currently on screen
