### ISSUE TITLE
reversePosition for v3.0.0

### ISSUE THREAD

**Issue by yigithanyucedag** [tongyy/react-native-draggable#54]
I need to use reversePosition function in version v3.0.0. Could you implement it?

**Comment by tongyy** [comment]
Since we refactored Draggable with react hooks, the methods don't support anymore.
#55 you can use the new callback function **onReverse**  and shouldReverse instead

`
<Button
        title={`Reverse Draggable01`}
        onPress={() => {
          setShouldReverse(true);
        }}
      />
`
`
<Draggable renderText="Draggable01" shouldReverse={shouldReverse} reverseCallback={()=>setShouldReverse(false)}/>
`
you also can reverse Draggable with offset x and y. by default, {x:0, y:0}
`
<Draggable renderText="Draggable01" shouldReverse={shouldReverse} reverseCallback={()=>{
setShouldReverse(false);
return {x:123, y:456};
}/>
`

**Comment by tongyy** [comment]
version v3.2.0 published

**Comment by lcundiff** [comment]
`<Button title={Reverse Draggable01} onPress={() => { setShouldReverse(true); }} />
<Draggable renderText="Draggable01" shouldReverse={shouldReverse} onReverse={()=>setShouldReverse(false)}/>`

This is not working for me. If you click the button, nothing will happen until you try to trigger the onRelease function since onReverse is not fired until then. 
Also only 2nd example of Draggable will work for typescript since it has a non-void return type. 

Is there a way to trigger the draggable to reverse without manually clicking and releasing? If a callback could be added that reverses the position, that would be extremely helpful. I haven't been able to manually override the position by adjusting the style, so currently I have no way of reversing its position programatically. 

Any help is appreciated.
